# ----------------------------------------
# Created on: Mon Oct 10 20:55:57 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/Program_Files/modeltech64_10.4/pango_sim_libraries/usim"
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/i2c_config.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/i2c_master_bit_ctrl.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/i2c_master_byte_ctrl.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/i2c_master_defines.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/i2c_master_top.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/i2c_master/timescale.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/aq_axi_master.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/cmos_8_16bit.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/cmos_write_req_gen.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/color_bar.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/frame_fifo_read.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/frame_fifo_write.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/frame_read_write.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/lut_ov5640_rgb565_1024_768.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/top.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/video_define.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/sources_1/video_timing_data.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/dvi_tx/dvi_encoder.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/dvi_tx/encode.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/dvi_tx/serdes_4b_10to1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrc_apb_reset_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrc_reset_ctrl_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrc_top_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrphy_dll_update_ctrl_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrphy_reset_ctrl_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrphy_training_ctrl_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_ddrphy_update_ctrl_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_phy_io_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/rtl/ipsl_hmic_h_phy_top_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/ddr3/ddr3.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/pll/pll_50_400_v1_1.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/video_pll/video_pll.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_16i_64o_512/rtl/ipml_sdpram_v1_5_afifo_16i_64o_512.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_v1_5_afifo_16i_64o_512.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_16i_64o_512/afifo_16i_64o_512.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_64i_16o_128/rtl/ipml_sdpram_v1_5_afifo_64i_16o_128.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_v1_5_afifo_64i_16o_128.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_64i_16o_128/afifo_64i_16o_128.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/fifo_tb.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/source/frame_write_read.v" -work work
vlog   "E:/Arm/purple_light/14_1_ddr3_ov5640_hdmi/ipcore/afifo_16i_64o_512/afifo_16i_64o_512_tb.v" -work work

# ----------------------------------------
