# ----------------------------------------
# Created on: Mon Oct 10 20:55:57 2022
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work -L usim fifo_tb usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 50ms

# ----------------------------------------
